# ============================================
# Local Variables for Detection Rules
# ============================================
# This file is AUTO-GENERATED by scripts/generate_locals.py
# DO NOT EDIT MANUALLY - Changes will be overwritten
# 
# To add new rules:
# 1. Add Sigma rule YAML to sigma_rules/
# 2. Run the CI/CD pipeline or manually run: python3 scripts/generate_locals.py

locals {
  # ============================================
  # Common Alert Settings
  # ============================================
  alert_type       = "number of events"
  alert_comparator = "greater than"
  actions          = "email"

  # ============================================
  # Detection Rules Configuration
  # ============================================
  detection_rules = {

    # Office Application Spawning Suspicious Processes
    office_spawning_suspicious_process = {
      name        = "Office Application Spawning Suspicious Processes"
      description = "Detects Microsoft Office applications spawning unusual child processes" # Truncated to 200 chars
      spl_file    = "office_spawning_suspicious_process.spl"

      # Scheduling
      cron_schedule          = "*/5 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "critical"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: Office Application Spawning Suspicious Processes"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Office Application Spawning Suspicious Processes
        Severity: CRITICAL
        Description: Detects Microsoft Office applications spawning unusual child processes

        Please investigate in Splunk.
      EOT
    }

    # Potential Multi-Stage Attack Chain
    multi_stage_attack_chain = {
      name        = "Potential Multi-Stage Attack Chain"
      description = "Correlates multiple suspicious activities from the same source" # Truncated to 200 chars
      spl_file    = "multi_stage_attack_chain.spl"

      # Scheduling
      cron_schedule          = "*/5 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "critical"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: Potential Multi-Stage Attack Chain"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Potential Multi-Stage Attack Chain
        Severity: CRITICAL
        Description: Correlates multiple suspicious activities from the same source

        Please investigate in Splunk.
      EOT
    }

    # Security Tool Tampering
    security_tool_tampering = {
      name        = "Security Tool Tampering"
      description = "Detects attempts to disable or modify security tools" # Truncated to 200 chars
      spl_file    = "security_tool_tampering.spl"

      # Scheduling
      cron_schedule          = "*/5 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "critical"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: Security Tool Tampering"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Security Tool Tampering
        Severity: CRITICAL
        Description: Detects attempts to disable or modify security tools

        Please investigate in Splunk.
      EOT
    }

    # Windows Event Log Cleared
    windows_event_log_cleared = {
      name        = "Windows Event Log Cleared"
      description = "Detects clearing of Windows event logs" # Truncated to 200 chars
      spl_file    = "windows_event_log_cleared.spl"

      # Scheduling
      cron_schedule          = "*/5 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "critical"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: Windows Event Log Cleared"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Windows Event Log Cleared
        Severity: CRITICAL
        Description: Detects clearing of Windows event logs

        Please investigate in Splunk.
      EOT
    }

    # Data Exfiltration via DNS
    dns_exfiltration_detection = {
      name        = "Data Exfiltration via DNS"
      description = "Detects potential DNS tunneling or exfiltration" # Truncated to 200 chars
      spl_file    = "dns_exfiltration_detection.spl"

      # Scheduling
      cron_schedule          = "*/15 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "high"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: Data Exfiltration via DNS"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Data Exfiltration via DNS
        Severity: HIGH
        Description: Detects potential DNS tunneling or exfiltration

        Please investigate in Splunk.
      EOT
    }

    # Encoded/Obfuscated Command Execution
    encoded_obfuscated_command_execution = {
      name        = "Encoded/Obfuscated_Command_Execution"
      description = "Detects execution of encoded or obfuscated commands" # Truncated to 200 chars
      spl_file    = "encoded_obfuscated_command_execution.spl"

      # Scheduling
      cron_schedule          = "*/15 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "high"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: Encoded/Obfuscated Command Execution"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Encoded/Obfuscated Command Execution
        Severity: HIGH
        Description: Detects execution of encoded or obfuscated commands

        Please investigate in Splunk.
      EOT
    }

    # Excessive Failed Login Attempts
    failed_login_attempts = {
      name        = "Excessive Failed Login Attempts"
      description = "Detects multiple failed login attempts indicating potential brute force attack" # Truncated to 200 chars
      spl_file    = "failed_login_attempts.spl"

      # Scheduling
      cron_schedule          = "*/15 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "high"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: Excessive Failed Login Attempts"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Excessive Failed Login Attempts
        Severity: HIGH
        Description: Detects multiple failed login attempts indicating potential brute force attack

        Please investigate in Splunk.
      EOT
    }

    # Kerberoasting Activity
    kerberoasting_activity = {
      name        = "Kerberoasting Activity"
      description = "Detects potential Kerberoasting attacks through RC4 ticket requests" # Truncated to 200 chars
      spl_file    = "kerberoasting_activity.spl"

      # Scheduling
      cron_schedule          = "*/15 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "high"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: Kerberoasting Activity"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Kerberoasting Activity
        Severity: HIGH
        Description: Detects potential Kerberoasting attacks through RC4 ticket requests

        Please investigate in Splunk.
      EOT
    }

    # Lateral Movement via Admin Shares
    lateral_movement_admin_shares = {
      name        = "Lateral Movement via Admin Shares"
      description = "Detects access to administrative shares for lateral movement" # Truncated to 200 chars
      spl_file    = "lateral_movement_admin_shares.spl"

      # Scheduling
      cron_schedule          = "*/15 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "high"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: Lateral Movement via Admin Shares"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Lateral Movement via Admin Shares
        Severity: HIGH
        Description: Detects access to administrative shares for lateral movement

        Please investigate in Splunk.
      EOT
    }

    # Privilege Escalation via Token Manipulation
    privilege_escalation_token_manipulation = {
      name        = "Privilege Escalation via Token Manipulation"
      description = "Detects attempts to manipulate access tokens for privilege escalation" # Truncated to 200 chars
      spl_file    = "privilege_escalation_token_manipulation.spl"

      # Scheduling
      cron_schedule          = "*/15 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "high"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: Privilege Escalation via Token Manipulation"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Privilege Escalation via Token Manipulation
        Severity: HIGH
        Description: Detects attempts to manipulate access tokens for privilege escalation

        Please investigate in Splunk.
      EOT
    }

    # Registry Run Key Modification
    registry_run_key_modification = {
      name        = "Registry Run Key Modification"
      description = "Detects modifications to common autostart registry keys" # Truncated to 200 chars
      spl_file    = "registry_run_key_modification.spl"

      # Scheduling
      cron_schedule          = "*/15 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "high"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: Registry Run Key Modification"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Registry Run Key Modification
        Severity: HIGH
        Description: Detects modifications to common autostart registry keys

        Please investigate in Splunk.
      EOT
    }

    # Remote WMI Execution
    remote_wmi_execution = {
      name        = "Remote WMI Execution"
      description = "Detects remote command execution via WMI" # Truncated to 200 chars
      spl_file    = "remote_wmi_execution.spl"

      # Scheduling
      cron_schedule          = "*/15 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "high"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: Remote WMI Execution"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Remote WMI Execution
        Severity: HIGH
        Description: Detects remote command execution via WMI

        Please investigate in Splunk.
      EOT
    }

    # Suspicious Email Attachment Execution
    suspicious_email_attachment_execution = {
      name        = "Suspicious Email Attachment Execution"
      description = "Detects execution of files from email attachment directories with suspicious extensions" # Truncated to 200 chars
      spl_file    = "suspicious_email_attachment_execution.spl"

      # Scheduling
      cron_schedule          = "*/15 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "high"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: Suspicious Email Attachment Execution"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Suspicious Email Attachment Execution
        Severity: HIGH
        Description: Detects execution of files from email attachment directories with suspicious extensions

        Please investigate in Splunk.
      EOT
    }

    # Suspicious PowerShell Execution
    suspicious_powershell = {
      name        = "Suspicious PowerShell Execution"
      description = "Detects PowerShell commands with obfuscation, encoding, or download capabilities." # Truncated to 200 chars
      spl_file    = "suspicious_powershell.spl"

      # Scheduling
      cron_schedule          = "*/15 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "high"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: Suspicious PowerShell Execution"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Suspicious PowerShell Execution
        Severity: HIGH
        Description: Detects PowerShell commands with obfuscation, encoding, or download capabilities.

        Please investigate in Splunk.
      EOT
    }

    # Suspicious Scheduled Task Creation
    suspicious_scheduled_task_creation = {
      name        = "Suspicious Scheduled Task Creation"
      description = "Detects creation of scheduled tasks with suspicious characteristics" # Truncated to 200 chars
      spl_file    = "suspicious_scheduled_task_creation.spl"

      # Scheduling
      cron_schedule          = "*/15 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "high"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: Suspicious Scheduled Task Creation"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Suspicious Scheduled Task Creation
        Severity: HIGH
        Description: Detects creation of scheduled tasks with suspicious characteristics

        Please investigate in Splunk.
      EOT
    }

    # UAC Bypass Attempt
    uac_bypass_attempt = {
      name        = "UAC Bypass Attempt"
      description = "Detects known UAC bypass techniques" # Truncated to 200 chars
      spl_file    = "uac_bypass_attempt.spl"

      # Scheduling
      cron_schedule          = "*/15 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "high"
      alert_threshold     = "0"
      alert_email_subject = "SIEM Alert: UAC Bypass Attempt"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: UAC Bypass Attempt
        Severity: HIGH
        Description: Detects known UAC bypass techniques

        Please investigate in Splunk.
      EOT
    }

    # Data Archiving Activity
    data_archiving_activity = {
      name        = "Data Archiving Activity"
      description = "Detects creation of archives that may contain sensitive data" # Truncated to 200 chars
      spl_file    = "data_archiving_activity.spl"

      # Scheduling
      cron_schedule          = "0 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "medium"
      alert_threshold     = "1"
      alert_email_subject = "SIEM Alert: Data Archiving Activity"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Data Archiving Activity
        Severity: MEDIUM
        Description: Detects creation of archives that may contain sensitive data

        Please investigate in Splunk.
      EOT
    }

    # Local Account Creation
    local_account_creation = {
      name        = "Local Account Creation"
      description = "Detects creation of new local user accounts" # Truncated to 200 chars
      spl_file    = "local_account_creation.spl"

      # Scheduling
      cron_schedule          = "0 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "medium"
      alert_threshold     = "1"
      alert_email_subject = "SIEM Alert: Local Account Creation"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Local Account Creation
        Severity: MEDIUM
        Description: Detects creation of new local user accounts

        Please investigate in Splunk.
      EOT
    }

    # Local Account Enumeration
    local_account_enumeration = {
      name        = "Local Account Enumeration"
      description = "Detects enumeration of local accounts on systems" # Truncated to 200 chars
      spl_file    = "local_account_enumeration.spl"

      # Scheduling
      cron_schedule          = "0 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "medium"
      alert_threshold     = "1"
      alert_email_subject = "SIEM Alert: Local Account Enumeration"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Local Account Enumeration
        Severity: MEDIUM
        Description: Detects enumeration of local accounts on systems

        Please investigate in Splunk.
      EOT
    }

    # Network Reconnaissance
    network_reconnaissance = {
      name        = "Network Reconnaissance"
      description = "Detects reconnaissance activities to discover remote systems" # Truncated to 200 chars
      spl_file    = "network_reconnaissance.spl"

      # Scheduling
      cron_schedule          = "0 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "medium"
      alert_threshold     = "1"
      alert_email_subject = "SIEM Alert: Network Reconnaissance"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Network Reconnaissance
        Severity: MEDIUM
        Description: Detects reconnaissance activities to discover remote systems

        Please investigate in Splunk.
      EOT
    }

    # Suspicious Command Shell Activity
    suspicious_command_shell_activity = {
      name        = "Suspicious Command Shell Activity"
      description = "Detects suspicious cmd.exe usage including reconnaissance and lateral movement commands" # Truncated to 200 chars
      spl_file    = "suspicious_command_shell_activity.spl"

      # Scheduling
      cron_schedule          = "0 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "medium"
      alert_threshold     = "1"
      alert_email_subject = "SIEM Alert: Suspicious Command Shell Activity"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Suspicious Command Shell Activity
        Severity: MEDIUM
        Description: Detects suspicious cmd.exe usage including reconnaissance and lateral movement commands

        Please investigate in Splunk.
      EOT
    }

    # Suspicious Local Admin Activity
    suspicious_local_admin_activity = {
      name        = "Suspicious Local Admin Activity"
      description = "Detects unusual activity from local administrator accounts" # Truncated to 200 chars
      spl_file    = "suspicious_local_admin_activity.spl"

      # Scheduling
      cron_schedule          = "0 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "medium"
      alert_threshold     = "1"
      alert_email_subject = "SIEM Alert: Suspicious Local Admin Activity"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Suspicious Local Admin Activity
        Severity: MEDIUM
        Description: Detects unusual activity from local administrator accounts

        Please investigate in Splunk.
      EOT
    }

    # Windows Defender Threat Detection Disabled
    windows_defender_disabled = {
      name        = "Windows Defender Threat Detection Disabled"
      description = "This rule detects Windows Defender disabling." # Truncated to 200 chars
      spl_file    = "windows_defender_disabled.spl"

      # Scheduling
      cron_schedule          = "0 * * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "medium"
      alert_threshold     = "1"
      alert_email_subject = "SIEM Alert: Windows Defender Threat Detection Disabled"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Windows Defender Threat Detection Disabled
        Severity: MEDIUM
        Description: This rule detects Windows Defender disabling.

        Please investigate in Splunk.
      EOT
    }

    # Process Enumeration
    process_enumeration = {
      name        = "Process Enumeration"
      description = "Detects excessive process enumeration activity" # Truncated to 200 chars
      spl_file    = "process_enumeration.spl"

      # Scheduling
      cron_schedule          = "0 */6 * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "low"
      alert_threshold     = "5"
      alert_email_subject = "SIEM Alert: Process Enumeration"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Process Enumeration
        Severity: LOW
        Description: Detects excessive process enumeration activity

        Please investigate in Splunk.
      EOT
    }

    # Screen Capture Tools Execution
    screen_capture_execution = {
      name        = "Screen Capture Tools Execution"
      description = "Detects execution of screen capture utilities" # Truncated to 200 chars
      spl_file    = "screen_capture_execution.spl"

      # Scheduling
      cron_schedule          = "0 */6 * * *"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity      = "low"
      alert_threshold     = "5"
      alert_email_subject = "SIEM Alert: Screen Capture Tools Execution"
      alert_email_message = <<-EOT
        A security event has been detected.

        Rule: Screen Capture Tools Execution
        Severity: LOW
        Description: Detects execution of screen capture utilities

        Please investigate in Splunk.
      EOT
    }
  }
}
