name: "Cache Terraform Providers"
description: "Restores or seeds the .terraform provider cache"

runs:
  using: "composite"
  steps:
    - name: Cache Terraform Providers
      uses: actions/cache@v4
      with:
        path: terraform/.terraform
        key: terraform-providers-${{ runner.os }}-${{ hashFiles('terraform/.terraform.lock.hcl') }}
        restore-keys: |
          terraform-providers-${{ runner.os }}-