#!/usr/bin/env python3
"""
Generate Terraform locals.tf from Sigma rules
"""
import yaml
import os
import glob
from pathlib import Path


def parse_sigma_rule(rule_path):
    """Parse a Sigma rule and extract metadata"""
    with open(rule_path, 'r') as f:
        rule = yaml.safe_load(f)

    # Extract key information
    title = rule.get('title', 'Unknown Rule')
    description = rule.get('description', '')
    level = rule.get('level', 'medium')

    # Generate key from filename
    filename = Path(rule_path).stem
    key = filename.lower().replace('-', '_').replace(' ', '_')

    # Map Sigma level to alert severity
    severity_map = {
        'critical': 'critical',
        'high': 'high',
        'medium': 'medium',
        'low': 'low',
        'informational': 'low'
    }
    severity = severity_map.get(level, 'medium')

    # Map severity to threshold
    threshold_map = {
        'critical': '0',
        'high': '0',
        'medium': '1',
        'low': '5'
    }
    threshold = threshold_map.get(severity, '1')

    # Map severity to schedule
    schedule_map = {
        'critical': '*/5 * * * *',  # Every 5 minutes
        'high': '*/15 * * * *',  # Every 15 minutes
        'medium': '0 * * * *',  # Hourly
        'low': '0 */6 * * *'  # Every 6 hours
    }
    schedule = schedule_map.get(severity, '0 * * * *')

    return {
        'key': key,
        'name': title,
        'description': description,
        'severity': severity,
        'threshold': threshold,
        'schedule': schedule,
        'spl_file': f'{filename}.spl'
    }


def generate_locals_tf(rules):
    """Generate locals.tf content"""

    tf_content = '''# ============================================
    # Local Variables for Detection Rules
    # ============================================
    # This file is AUTO-GENERATED by scripts/generate_locals.py
    # DO NOT EDIT MANUALLY - Changes will be overwritten
    # 
    # To add new rules:
    # 1. Add Sigma rule YAML to sigma_rules/
    # 2. Run the CI/CD pipeline or manually run: python3 scripts/generate_locals.py
    
    locals {
      # ============================================
      # Common Alert Settings
      # ============================================
      alert_type       = "number of events"
      alert_comparator = "greater than"
      actions          = "email"
    
      # ============================================
      # Detection Rules Configuration
      # ============================================
      detection_rules = {
    '''

    # Sort rules by severity then name
    severity_order = {'critical': 0, 'high': 1, 'medium': 2, 'low': 3}
    sorted_rules = sorted(rules, key=lambda x: (severity_order.get(x['severity'], 4), x['name']))

    for rule in sorted_rules:
        tf_content += f'''
    # {rule['name']}
    {rule['key']} = {{
      name                  = "{rule['name']}"
      description           = "{rule['description'][:200]}"  # Truncated to 200 chars
      spl_file             = "{rule['spl_file']}"

      # Scheduling
      cron_schedule          = "{rule['schedule']}"
      dispatch_earliest_time = "-1h"
      dispatch_latest_time   = "now"

      # Alert settings
      alert_severity        = "{rule['severity']}"
      alert_threshold       = "{rule['threshold']}"
      alert_email_subject   = "SIEM Alert: {rule['name']}"
      alert_email_message   = <<-EOT
        A security event has been detected.

        Rule: {rule['name']}
        Severity: {rule['severity'].upper()}
        Description: {rule['description'][:150]}

        Please investigate in Splunk.
      EOT
    }}
'''

    tf_content += '''  }
}
'''

    return tf_content


def main():
    """Main function"""
    # Find all Sigma rules
    sigma_dir = 'sigma_rules'
    rule_files = glob.glob(f'{sigma_dir}/**/*.yml', recursive=True)

    if not rule_files:
        print(f"ERROR: No Sigma rules found in {sigma_dir}/")
        exit(1)

    print(f"Found {len(rule_files)} Sigma rule(s)")

    # Parse all rules
    rules = []
    for rule_file in rule_files:
        try:
            rule = parse_sigma_rule(rule_file)
            rules.append(rule)
            print(f"  Parsed: {rule['name']}")
        except Exception as e:
            print(f"  ERROR parsing {rule_file}: {e}")
            continue

    if not rules:
        print("ERROR: No rules successfully parsed")
        exit(1)

    # Generate locals.tf
    tf_content = generate_locals_tf(rules)

    # Write to file
    output_file = 'terraform/locals.tf'
    os.makedirs('terraform', exist_ok=True)

    with open(output_file, 'w') as f:
        f.write(tf_content)

    print(f"\nSuccessfully generated {output_file} with {len(rules)} rule(s)")


if __name__ == '__main__':
    main()